# Generated by Django 4.2.16 on 2026-05-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercostoption',
            name='quote_document',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_quotes/'),
        ),
    ]
