# Generated by Django 4.2.16 on 2026-05-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_suppliercostoption_quote_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliercostoption',
            name='quote_document',
        ),
        migrations.AddField(
            model_name='suppliercostoption',
            name='photo_or_document',
            field=models.FileField(blank=True, null=True, upload_to='supplier_quotes/', verbose_name='Photo or Document'),
        ),
    ]
