# Generated by Django 4.2.16 on 2026-05-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_suppliercostoption_quote_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='make_or_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_or_document',
            field=models.FileField(blank=True, null=True, upload_to='product_docs/'),
        ),
    ]
