# Generated by Django 4.2.16 on 2026-05-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_product_product_image_product_make_or_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercostoption',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
