# Generated by Django 4.2.16 on 2026-05-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_suppliercostoption_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercostoption',
            name='product_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Product Link'),
        ),
        migrations.AlterField(
            model_name='suppliercostoption',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
