# Generated by Django 4.2.16 on 2026-05-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_suppliercostoption_product_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remark',
            field=models.TextField(blank=True, help_text='Optional remark or notes for this product.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.CharField(default='Pcs', max_length=50),
        ),
    ]
