# Generated by Django 4.2.16 on 2026-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_productbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercostoption',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes for this supplier option.', null=True),
        ),
    ]
