# Generated by Django 4.2.16 on 2026-06-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_suppliercostoption_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
