# Generated by Django 4.2.16 on 2026-06-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_product_is_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercostoption',
            name='selling_price_ex_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='suppliercostoption',
            name='selling_price_inc_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
