# Generated by Django 4.2.16 on 2026-06-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_suppliercostoption_selling_price_ex_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliercostoption',
            name='selling_price_ex_gst',
        ),
        migrations.RemoveField(
            model_name='suppliercostoption',
            name='selling_price_inc_gst',
        ),
        migrations.AddField(
            model_name='product',
            name='buying_price_ex_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='buying_price_inc_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price_ex_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price_inc_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
