# Generated by Django 4.2.16 on 2026-06-06 06:58

from django.db import migrations


def map_order_statuses(apps, schema_editor):
    Order = apps.get_model('tracker', 'Order')
    # OPEN_NOT_STARTED -> OPEN
    Order.objects.filter(order_status='OPEN_NOT_STARTED').update(order_status='OPEN')
    # OPEN_STARTED -> SOURCING
    Order.objects.filter(order_status='OPEN_STARTED').update(order_status='SOURCING')
    # OPEN_DELIVERED -> SHIPPED
    Order.objects.filter(order_status='OPEN_DELIVERED').update(order_status='SHIPPED')

def reverse_map_order_statuses(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_order_order_status_task_notification'),
    ]

    operations = [
        migrations.RunPython(map_order_statuses, reverse_map_order_statuses),
    ]
