# Generated by Django 4.2.16 on 2026-06-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20260606_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('SOURCING', 'SOURCING'), ('PROCURED', 'PROCURED'), ('SHIPPED', 'SHIPPED'), ('RECEIVED', 'RECEIVED'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=50),
        ),
    ]
