# Generated by Django 4.2.16 on 2026-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_internalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalnote',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internalnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
