# Generated by Django 4.2.16 on 2026-06-06 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0019_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('status_code', models.IntegerField(default=500)),
                ('error_type', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField()),
                ('url', models.CharField(max_length=2000)),
                ('http_method', models.CharField(max_length=10)),
                ('query_params', models.TextField(blank=True, null=True)),
                ('post_data', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
