# Generated by Django 4.2.16 on 2026-06-06 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0020_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFieldVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_selling_price', models.BooleanField(default=True)),
                ('can_see_purchase_price', models.BooleanField(default=True)),
                ('can_see_profit_loss', models.BooleanField(default=True)),
                ('can_see_lot_total', models.BooleanField(default=True)),
                ('can_see_internal_notes', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_visibility', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
