# Generated by Django 5.2.14 on 2026-06-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_userfieldvisibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfieldvisibility',
            name='pref_show_internal_notes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userfieldvisibility',
            name='pref_show_lot_total',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userfieldvisibility',
            name='pref_show_profit_loss',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userfieldvisibility',
            name='pref_show_purchase_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userfieldvisibility',
            name='pref_show_selling_price',
            field=models.BooleanField(default=True),
        ),
    ]
