# Generated by Django 5.2.14 on 2026-06-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_priceapprovalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='minimum_profit_margin',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Minimum required profit margin (%) for automatic price approval.', max_digits=5),
        ),
        migrations.DeleteModel(
            name='PriceApprovalRequest',
        ),
    ]
