# Generated by Django 5.2.14 on 2026-06-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_userreferencedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stage',
            field=models.CharField(blank=True, choices=[('REQ_RECEIVED', 'Requirement Received'), ('QUOT_GIVEN', 'Quotation Given'), ('PO_RECEIVED', 'PO Received'), ('PI_GIVEN', 'PI Given'), ('PROD_GIVEN', 'Product Given'), ('INV_GIVEN', 'Invoice Given'), ('REQ_SEARCHING', 'Requirement Searching'), ('QUOT_RECEIVED', 'Quotation Received'), ('PO_GIVEN', 'PO Given'), ('PI_RECEIVED', 'PI Received'), ('PROD_RECEIVED', 'Product Received'), ('INV_RECEIVED', 'Invoice Received')], help_text='Current processing stage for this product (Customer or Supplier side).', max_length=30, null=True),
        ),
    ]
