# Generated by Django 5.2.14 on 2026-06-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_product_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_stage',
        ),
        migrations.AddField(
            model_name='product',
            name='customer_stage',
            field=models.CharField(blank=True, choices=[('REQ_RECEIVED', 'Requirement Received'), ('QUOT_GIVEN', 'Quotation Given'), ('PO_RECEIVED', 'PO Received'), ('PI_GIVEN', 'PI Given'), ('PROD_GIVEN', 'Product Given'), ('INV_GIVEN', 'Invoice Given')], help_text='Current stage on the Customer side for this product.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_stage',
            field=models.CharField(blank=True, choices=[('REQ_SEARCHING', 'Requirement Searching'), ('QUOT_RECEIVED', 'Quotation Received'), ('PO_GIVEN', 'PO Given'), ('PI_RECEIVED', 'PI Received'), ('PROD_RECEIVED', 'Product Received'), ('INV_RECEIVED', 'Invoice Received')], help_text='Current stage on the Supplier side for this product.', max_length=30, null=True),
        ),
    ]
